name: Auto Approve & Merge Everything

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  auto-approve-all:
    name: Auto approve all PRs
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Auto approve ALL PRs (no conditions)
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge-all:
    name: Auto merge all approved PRs
    runs-on: ubuntu-latest
    needs: auto-approve-all
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Wait for potential checks
        run: sleep 10

      - name: Auto merge ALL PRs with admin bypass
        run: |
          echo "Merging PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --admin \
            --squash \
            --delete-branch \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup-failed-runs:
    name: Auto-cleanup failed workflow runs
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Cleanup old workflow runs
        run: |
          # ลบ workflow runs ที่ล้มเหลวเก่าๆ
          gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[].id' | head -20 | \
          while read run_id; do
            gh api --method DELETE repos/${{ github.repository }}/actions/runs/$run_id || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}