name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run lightweight build checks
        id: checks
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          python -m compileall .

      - name: Publish commit status
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outcome = '${{ steps.checks.outcome }}';
            const state = outcome === 'success' ? 'success' : 'failure';
            const description = state === 'success' ? 'Lightweight checks passed' : 'Lightweight checks failed';
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state,
              context: 'ci',
              description,
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            });
            if (state === 'failure') {
              core.setFailed(description);
            }
