name: gitleaks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 1'

permissions:
  contents: read

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for secrets with Gitleaks
        id: scan
        continue-on-error: true
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --source "." --verbose

      - name: Publish commit status
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outcome = '${{ steps.scan.outcome }}';
            const state = outcome === 'success' ? 'success' : 'failure';
            const description = state === 'success' ? 'No secrets detected' : 'Potential secrets found';
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state,
              context: 'gitleaks',
              description,
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            });
            if (state === 'failure') {
              core.setFailed(description);
            }
