# .github/workflows/security.yml  (เฉพาะ job pip-audit)
pip-audit:
  if: ${{ hashFiles('requirements.txt') != '' }}   # ไม่มีไฟล์ = ข้ามทั้งงาน
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12', cache: 'pip' }
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install pip-audit
      run: pip install pip-audit
    - name: Run pip-audit
      run: pip-audit -r requirements.txt --strict
