name: Security

on:
  pull_request: { branches: ["main"] }
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  pip-audit:
    name: Python dependency audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit
        run: |
          set -e
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt --strict
          else
            echo "No requirements.txt found, auditing environment packages"
            pip-audit --strict
